// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCop8-zTdzQOn7z4r04jTajQC2VI8Huj94',
    appId: '1:229132516134:web:e8967e5f6c7650c928dfe7',
    messagingSenderId: '229132516134',
    projectId: 'taskfant',
    authDomain: 'taskfant.firebaseapp.com',
    storageBucket: 'taskfant.appspot.com',
    measurementId: 'G-1TCQR2BDB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMqmfWxXURH11Hz-j4ZfKFl61VxulT6Kc',
    appId: '1:229132516134:android:cabe986c9a5a599c28dfe7',
    messagingSenderId: '229132516134',
    projectId: 'taskfant',
    storageBucket: 'taskfant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEdohNMkZSGQrWBRe1eRHWbqaFj0Gug-M',
    appId: '1:229132516134:ios:b5fbf978677abb0828dfe7',
    messagingSenderId: '229132516134',
    projectId: 'taskfant',
    storageBucket: 'taskfant.appspot.com',
    androidClientId: '229132516134-i636b2iqvfk22cnima6eg5b1nenktc4k.apps.googleusercontent.com',
    iosClientId: '229132516134-2ebs70s1mssiu2q1u2nkl3rufb6qt6qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskFanIntegration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEdohNMkZSGQrWBRe1eRHWbqaFj0Gug-M',
    appId: '1:229132516134:ios:b5fbf978677abb0828dfe7',
    messagingSenderId: '229132516134',
    projectId: 'taskfant',
    storageBucket: 'taskfant.appspot.com',
    androidClientId: '229132516134-i636b2iqvfk22cnima6eg5b1nenktc4k.apps.googleusercontent.com',
    iosClientId: '229132516134-2ebs70s1mssiu2q1u2nkl3rufb6qt6qp.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskFanIntegration',
  );
}
